-- Migration 024 — Índice de emails (anexos / classificação)

CREATE TABLE emails_indice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero INTEGER,
  mes TEXT,
  data_email DATE,
  remetente TEXT,
  email_remetente TEXT,
  assunto TEXT,
  codigo_lead TEXT DEFAULT 'SEM-REF',
  tipo_doc TEXT,
  categoria TEXT,
  nome_ficheiro TEXT,
  pasta_lead TEXT,
  pasta_fornecedor TEXT,
  pasta_categoria TEXT,
  fornecedor TEXT,
  nome_original TEXT,
  tamanho_bytes BIGINT,
  content_type TEXT,
  notas TEXT,
  spam BOOLEAN NOT NULL DEFAULT false,
  contacto_normalizado TEXT,
  email_pai TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_emails_indice_data_email ON emails_indice (data_email);
CREATE INDEX idx_emails_indice_categoria ON emails_indice (categoria);
CREATE INDEX idx_emails_indice_fornecedor ON emails_indice (fornecedor);
CREATE INDEX idx_emails_indice_tipo_doc ON emails_indice (tipo_doc);
CREATE INDEX idx_emails_indice_spam ON emails_indice (spam);
CREATE INDEX idx_emails_indice_codigo_lead ON emails_indice (codigo_lead);

ALTER TABLE emails_indice ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role full access" ON emails_indice FOR ALL USING (true) WITH CHECK (true);

COMMENT ON TABLE emails_indice IS 'Índice de mensagens/anexos de email para classificação e pastas (leads, fornecedores)';

INSERT INTO audit_log (entidade_tipo, entidade_id, acao, metadata)
VALUES ('migration', '024', 'CREATE', '{"descricao": "tabela emails_indice"}'::jsonb);
